# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "UniquelyGrant"

# Tagline next to the site title
tagline: "Thoughts, ideas, and your daily dose of monologuing"

# A description of your site for social meta tag, search engines, and feed.xml
description: "BA¹ with a BS² in SD³ (Business Analyst¹; Bachelors of Science²; Software Development³: Just for clarity...)"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: /

# Sass
sass:
  sass_dir: _sass
  style: compressed

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://uniquelygrant.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus:

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: 

# Author information - author info at the bottom of the post
author_name: "Grant E. Weldon"
author_bio: "Can't I just be a person with opinions, founded or not?"
author_url:  "https://uniquelygrant.com"
author_location: "Somewheeeerrreee, over the raiiinboooowww"
author_image:

# Sidebar Add banner
banner_url: 
banner_image: 
banner_image_alt: 

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: 

# Social links in the site footer
twitter_url: 
facebook_url: 
github_url: "https://github.com/geweldon"
codepen_url: 
dribbble_url: 
medium_url:
instagram_url: 
pinterest_url: "
linkedin_url: "https://www.linkedin.com/in/grant-weldon-51721043/"
weibo_url: 

# http://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: '/blog/page:num/'
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
